server:
  port: 8030

spring:
  application:
    name: paper-service
  profiles:
    active: local

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/paper?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

  data:
    redis:
      host: localhost
      port: 6380

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/paper?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

  data:
    redis:
      host: localhost
      port: 6380

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true