server:
  port: 9000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/api/members/**
        - id: diary-service
          uri: lb://diary-service
          predicates:
            - Path=/api/diaries/**
        - id: paper-service
          uri: lb://paper-service
          predicates:
            - Path=/api/papers/**
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/api/comments/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8100/eureka