server:
  port: 8100

spring:
  application:
    name: discovery-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/

  server:
    wait-time-in-ms-when-sync-empty: 5